# CMake generated Testfile for 
# Source directory: /home/runner/work/BlockChainDrachma/BlockChainDrachma
# Build directory: /home/runner/work/BlockChainDrachma/BlockChainDrachma/_codeql_build_dir
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
include("/home/runner/work/BlockChainDrachma/BlockChainDrachma/_codeql_build_dir/schnorr_vectors_test[1]_include.cmake")
include("/home/runner/work/BlockChainDrachma/BlockChainDrachma/_codeql_build_dir/difficulty_gtest[1]_include.cmake")
include("/home/runner/work/BlockChainDrachma/BlockChainDrachma/_codeql_build_dir/pow_check_gtest[1]_include.cmake")
include("/home/runner/work/BlockChainDrachma/BlockChainDrachma/_codeql_build_dir/mempool_stress_test[1]_include.cmake")
include("/home/runner/work/BlockChainDrachma/BlockChainDrachma/_codeql_build_dir/wallet_sign_gtest[1]_include.cmake")
include("/home/runner/work/BlockChainDrachma/BlockChainDrachma/_codeql_build_dir/p2p_dos_sim_test[1]_include.cmake")
include("/home/runner/work/BlockChainDrachma/BlockChainDrachma/_codeql_build_dir/p2p_multinode_gtest[1]_include.cmake")
include("/home/runner/work/BlockChainDrachma/BlockChainDrachma/_codeql_build_dir/bloom_filter_gtest[1]_include.cmake")
include("/home/runner/work/BlockChainDrachma/BlockChainDrachma/_codeql_build_dir/rpc_server_test[1]_include.cmake")
include("/home/runner/work/BlockChainDrachma/BlockChainDrachma/_codeql_build_dir/regtest_mode_test[1]_include.cmake")
include("/home/runner/work/BlockChainDrachma/BlockChainDrachma/_codeql_build_dir/regtest_private_chain_test[1]_include.cmake")
include("/home/runner/work/BlockChainDrachma/BlockChainDrachma/_codeql_build_dir/crosschain_bridge_gtest[1]_include.cmake")
include("/home/runner/work/BlockChainDrachma/BlockChainDrachma/_codeql_build_dir/sidechain_evm_test[1]_include.cmake")
include("/home/runner/work/BlockChainDrachma/BlockChainDrachma/_codeql_build_dir/nft_precompile_test[1]_include.cmake")
include("/home/runner/work/BlockChainDrachma/BlockChainDrachma/_codeql_build_dir/peg_bridge_test[1]_include.cmake")
add_test(schnorr_test "/home/runner/work/BlockChainDrachma/BlockChainDrachma/_codeql_build_dir/schnorr_test")
set_tests_properties(schnorr_test PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/BlockChainDrachma/BlockChainDrachma/CMakeLists.txt;204;add_test;/home/runner/work/BlockChainDrachma/BlockChainDrachma/CMakeLists.txt;0;")
add_test(merkle_test "/home/runner/work/BlockChainDrachma/BlockChainDrachma/_codeql_build_dir/merkle_test")
set_tests_properties(merkle_test PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/BlockChainDrachma/BlockChainDrachma/CMakeLists.txt;212;add_test;/home/runner/work/BlockChainDrachma/BlockChainDrachma/CMakeLists.txt;0;")
add_test(supply_test "/home/runner/work/BlockChainDrachma/BlockChainDrachma/_codeql_build_dir/supply_test")
set_tests_properties(supply_test PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/BlockChainDrachma/BlockChainDrachma/CMakeLists.txt;216;add_test;/home/runner/work/BlockChainDrachma/BlockChainDrachma/CMakeLists.txt;0;")
add_test(retarget_test "/home/runner/work/BlockChainDrachma/BlockChainDrachma/_codeql_build_dir/retarget_test")
set_tests_properties(retarget_test PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/BlockChainDrachma/BlockChainDrachma/CMakeLists.txt;220;add_test;/home/runner/work/BlockChainDrachma/BlockChainDrachma/CMakeLists.txt;0;")
add_test(difficulty_adjust_test "/home/runner/work/BlockChainDrachma/BlockChainDrachma/_codeql_build_dir/difficulty_adjust_test")
set_tests_properties(difficulty_adjust_test PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/BlockChainDrachma/BlockChainDrachma/CMakeLists.txt;232;add_test;/home/runner/work/BlockChainDrachma/BlockChainDrachma/CMakeLists.txt;0;")
add_test(validation_tests "/home/runner/work/BlockChainDrachma/BlockChainDrachma/_codeql_build_dir/validation_tests")
set_tests_properties(validation_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/BlockChainDrachma/BlockChainDrachma/CMakeLists.txt;236;add_test;/home/runner/work/BlockChainDrachma/BlockChainDrachma/CMakeLists.txt;0;")
add_test(fork_resolution_test "/home/runner/work/BlockChainDrachma/BlockChainDrachma/_codeql_build_dir/fork_resolution_test")
set_tests_properties(fork_resolution_test PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/BlockChainDrachma/BlockChainDrachma/CMakeLists.txt;240;add_test;/home/runner/work/BlockChainDrachma/BlockChainDrachma/CMakeLists.txt;0;")
add_test(chainstate_tests "/home/runner/work/BlockChainDrachma/BlockChainDrachma/_codeql_build_dir/chainstate_tests")
set_tests_properties(chainstate_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/BlockChainDrachma/BlockChainDrachma/CMakeLists.txt;244;add_test;/home/runner/work/BlockChainDrachma/BlockChainDrachma/CMakeLists.txt;0;")
add_test(mempool_tests "/home/runner/work/BlockChainDrachma/BlockChainDrachma/_codeql_build_dir/mempool_tests")
set_tests_properties(mempool_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/BlockChainDrachma/BlockChainDrachma/CMakeLists.txt;248;add_test;/home/runner/work/BlockChainDrachma/BlockChainDrachma/CMakeLists.txt;0;")
add_test(block_validation_tests "/home/runner/work/BlockChainDrachma/BlockChainDrachma/_codeql_build_dir/block_validation_tests")
set_tests_properties(block_validation_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/BlockChainDrachma/BlockChainDrachma/CMakeLists.txt;260;add_test;/home/runner/work/BlockChainDrachma/BlockChainDrachma/CMakeLists.txt;0;")
add_test(p2p_integration_test "/home/runner/work/BlockChainDrachma/BlockChainDrachma/_codeql_build_dir/p2p_integration_test")
set_tests_properties(p2p_integration_test PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/BlockChainDrachma/BlockChainDrachma/CMakeLists.txt;264;add_test;/home/runner/work/BlockChainDrachma/BlockChainDrachma/CMakeLists.txt;0;")
add_test(anti_dos_tests "/home/runner/work/BlockChainDrachma/BlockChainDrachma/_codeql_build_dir/anti_dos_tests")
set_tests_properties(anti_dos_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/BlockChainDrachma/BlockChainDrachma/CMakeLists.txt;280;add_test;/home/runner/work/BlockChainDrachma/BlockChainDrachma/CMakeLists.txt;0;")
add_test(attacks_sim "/home/runner/work/BlockChainDrachma/BlockChainDrachma/_codeql_build_dir/attacks_sim")
set_tests_properties(attacks_sim PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/BlockChainDrachma/BlockChainDrachma/CMakeLists.txt;284;add_test;/home/runner/work/BlockChainDrachma/BlockChainDrachma/CMakeLists.txt;0;")
subdirs("_deps/leveldb-build")
subdirs("_deps/googletest-build")
