if(EXISTS "/home/runner/work/BlockChainDrachma/BlockChainDrachma/_codeql_build_dir/p2p_dos_sim_test[1]_tests.cmake")
  include("/home/runner/work/BlockChainDrachma/BlockChainDrachma/_codeql_build_dir/p2p_dos_sim_test[1]_tests.cmake")
else()
  add_test(p2p_dos_sim_test_NOT_BUILT p2p_dos_sim_test_NOT_BUILT)
endif()
