if(EXISTS "/home/runner/work/BlockChainDrachma/BlockChainDrachma/_codeql_build_dir/peg_bridge_test[1]_tests.cmake")
  include("/home/runner/work/BlockChainDrachma/BlockChainDrachma/_codeql_build_dir/peg_bridge_test[1]_tests.cmake")
else()
  add_test(peg_bridge_test_NOT_BUILT peg_bridge_test_NOT_BUILT)
endif()
