#!/bin/bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BINARY_DEFAULT="${ROOT_DIR}/build/drachma_node"
NETWORK=${NETWORK:-testnet}
DATADIR_DEFAULT="${HOME}/.drachma-${NETWORK}"
CONFIG_DEFAULT="${DATADIR_DEFAULT}/drachma.conf"
RPC_USER_DEFAULT=${RPC_USER:-drachma}
RPC_PASS_DEFAULT=${RPC_PASSWORD:-}

usage() {
  cat <<USAGE
Usage: $0 [-n <network>] [-b <binary>] [-d <datadir>] [-c <config>] [-- extra args]
  -n <network>  Network to join (testnet|mainnet) (default: ${NETWORK})
  -b <binary>   Path to node executable (default: ${BINARY_DEFAULT})
  -d <datadir>  Data directory (default: ${DATADIR_DEFAULT})
  -c <config>   Config file path (default: ${CONFIG_DEFAULT})

Creates a minimal config if none exists, then launches the node with the chosen
network and directories. Environment variables RPC_USER/RPC_PASSWORD override
credentials used for auto-generated configs.
USAGE
}

BINARY="$BINARY_DEFAULT"
DATADIR="$DATADIR_DEFAULT"
CONFIG="$CONFIG_DEFAULT"

while [[ $# -gt 0 ]]; do
  case "$1" in
    -h|--help) usage; exit 0 ;;
    -n) NETWORK="$2"; DATADIR_DEFAULT="${HOME}/.drachma-${NETWORK}"; CONFIG_DEFAULT="${DATADIR_DEFAULT}/drachma.conf"; DATADIR="$DATADIR_DEFAULT"; CONFIG="$CONFIG_DEFAULT"; shift 2 ;;
    -b) BINARY="$2"; shift 2 ;;
    -d) DATADIR="$2"; shift 2 ;;
    -c) CONFIG="$2"; shift 2 ;;
    --) shift; break ;;
    *) echo "Unknown option: $1" >&2; usage; exit 1 ;;
  esac
done

if [[ ! -x "$BINARY" ]]; then
  echo "Fatal: node binary not found at $BINARY" >&2
  echo "Build with scripts/build.sh and ensure the executable name matches."
  exit 1
fi

mkdir -p "$DATADIR"
if [[ ! -f "$CONFIG" ]]; then
  if [[ -z "$RPC_PASS_DEFAULT" ]]; then
    RPC_PASS_DEFAULT=$(tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 32)
  fi
  cat >"$CONFIG" <<CFG
# Auto-generated by start-node.sh
rpcuser=${RPC_USER_DEFAULT}
rpcpassword=${RPC_PASS_DEFAULT}
server=1
listen=1
network=${NETWORK}

# Uncomment to expose metrics
# metrics=1
# metricsport=9311
CFG
  chmod 600 "$CONFIG"
  echo "Created fresh config at $CONFIG (rpcuser=${RPC_USER_DEFAULT})"
fi

exec "$BINARY" --network "$NETWORK" -conf="$CONFIG" -datadir="$DATADIR" "$@"
